# Generated by Django 4.0.6 on 2023-09-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pricefinderapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, default='', related_name='custom_user_permissions', to='auth.permission'),
        ),
    ]
