# Generated by Django 4.0.6 on 2023-09-10 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricefinderapp', '0004_alter_customer_addressline1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='shippingstate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
