# Generated by Django 4.0.6 on 2023-09-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricefinderapp', '0005_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='milk', max_length=255),
            preserve_default=False,
        ),
    ]
