# Generated by Django 4.0.6 on 2023-09-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricefinderapp', '0006_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('₹', '₹'), ('$', '$'), ('€', '€')], default='₹', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('L', 'L'), ('kg', 'kg'), ('g', 'g'), ('', 'QTY')], default='', max_length=3),
        ),
    ]
