# Generated by Django 4.0.6 on 2023-09-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricefinderapp', '0012_customer_user_type_retailer_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('L', 'L'), ('kg', 'kg'), ('g', 'g'), ('', 'QTY')], default='', max_length=3),
        ),
    ]
