# Generated by Django 4.0.6 on 2023-09-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricefinderapp', '0013_customer_district_alter_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
